version: "3.5"
services:
  api:
    image: doraboateng/api-dev
    build:
      context: .
      target: dev
    command: air
    depends_on:
      - db
    env_file: ./.env
    ports:
      - "$APP_PORT:$APP_PORT"
    volumes:
      - .:/root/boateng-api
  db:
    environment:
      MYSQL_DATABASE: $MARIADB_DATABASE
      MYSQL_USER: $MARIADB_USERNAME
      MYSQL_PASSWORD: $MARIADB_PASSWORD
      MYSQL_ROOT_PASSWORD: $MARIADB_PASSWORD
    image: mariadb:10.4.6
    ports:
      - "$MARIADB_HOST_PORT:$MARIADB_PORT"
