version: "3"
services:
  api:
    image: doraboateng/api-build:latest
    command: bash -c "go get && go run main.go"
    depends_on:
      - db
    env_file: ./.env
    ports:
      - "$APP_PORT:$APP_PORT"
    volumes:
      - ./migrations:/go/src/github.com/doraboateng/api/migrations
      - ./src:/go/src/github.com/doraboateng/api/src
  db:
    environment:
      MYSQL_DATABASE: $MARIADB_DATABASE
      MYSQL_USER: $MARIADB_USERNAME
      MYSQL_PASSWORD: $MARIADB_PASSWORD
      MYSQL_ROOT_PASSWORD: $MARIADB_PASSWORD
    image: mariadb:10.4.6
    ports:
      - "$MARIADB_HOST_PORT:$MARIADB_PORT"
