version: "3.5"
services:
  api:
    image: doraboateng/api-dev:latest
    command: air
    depends_on:
      - db
      - graph
    env_file: .env
    ports:
      - "$APP_PORT:$APP_PORT"
    volumes:
      - .:/root/boateng-api
  db:
    environment:
      MYSQL_DATABASE: $MARIADB_DATABASE
      MYSQL_USER: $MARIADB_USERNAME
      MYSQL_PASSWORD: $MARIADB_PASSWORD
      MYSQL_ROOT_PASSWORD: $MARIADB_PASSWORD
    image: mariadb:10.4.6
    ports:
      - "$MARIADB_HOST_PORT:$MARIADB_PORT"
  graph:
    image: dgraph/standalone:v2.0.0-rc1
    ports:
      - 8000:8000
      - 8080:8080
      - 9080:9080
    volumes:
      - ./data:/tmp/dgraph-data
  # graph:
  #   image: janusgraph/janusgraph
  #   ports:
  #     - "$JANUSGRAPH_HOST_PORT:$JANUSGRAPH_PORT"
