# Reference: https://github.com/dgraph-io/dgraph/blob/master/dgraph/docker-compose.yml
version: "3.4"
services:

  # API
  api:
    image: doraboateng/api:dev
    build:
      context: "."
      target: dev
    command: air
    depends_on:
      - zero
      - alpha
    env_file: .env
    environment:
      BOATENG_ENV: local
      PORT: 8800
    networks:
      - shared_network
    ports:
      - "8800:8800"
    volumes:
      - .:/boateng-api:cached
    working_dir: /boateng-api

  # Dgraph Zero
  zero:
    # image: doraboateng/graph:${BOATENG_GRAPH_VERSION}
    image: dgraph/dgraph:${DGRAPH_VERSION}
    command: >-
      dgraph zero
        --bindall
        --enable_sentry=false
        --logtostderr
        --my=zero:5080
        --telemetry=false
    env_file: .env
    networks:
      - shared_network
    ports:
      - "6080:6080"
    volumes:
      - dgraph_volume:/dgraph:delegated

  # Dgraph Alpha
  alpha:
    # image: doraboateng/graph:${BOATENG_GRAPH_VERSION}
    image: dgraph/dgraph:${DGRAPH_VERSION}
    command: >-
      dgraph alpha
        --enable_sentry=false
        --logtostderr
        --lru_mb=1024
        --my=alpha:7080
        --telemetry=false
        --trace 1.0
        --whitelist localhost,10.0.0.0:10.255.255.255,172.16.0.0:172.31.255.255,192.168.0.0:192.168.255.255
        --zero=zero:5080
    env_file: .env
    networks:
      - shared_network
    depends_on:
      - zero
    ports:
      - 8080:8080
      - 7080:7080
    volumes:
      - dgraph_volume:/dgraph:delegated

networks:
  shared_network:

volumes:
  dgraph_volume:
