# Reference: https://github.com/dgraph-io/dgraph/blob/master/dgraph/docker-compose.yml
version: "3.4"
services:

  # API
  api:
    image: doraboateng/api:dev
    build:
      context: "."
      target: dev
    command: air
    depends_on:
      - zero
      - alpha
    env_file: .env
    ports:
      - "8800:8800"
    volumes:
      - .:/boateng-api:cached
    working_dir: /boateng-api

  # Dgraph Zero
  zero:
    image: doraboateng/graph:latest
    command: >-
      dgraph zero
        --bindall
        --block_rate 10
        --expose_trace
        --logtostderr
        --my=zero:5080
        --profile_mode block
        -v=2
    env_file: .env
    ports:
      - "8819:6080"
    volumes:
      - dgraph_volume:/dgraph:delegated

  # Dgraph Alpha
  alpha:
    image: doraboateng/graph:latest
    command: >-
      dgraph alpha
        --block_rate 10
        --expose_trace
        --logtostderr
        --lru_mb=1024
        --my=alpha:7080
        --profile_mode block
        --trace 1.0
        -v=2
        --zero=zero:5080
    env_file: .env
    depends_on:
      - zero
    ports:
      - 8817:8080
      - 8818:7080
    volumes:
      - dgraph_volume:/dgraph:delegated

  # Dgraph Ratel
  ratel:
    image: doraboateng/graph:latest
    command: dgraph-ratel -addr alpha:7080
    env_file: .env
    depends_on:
      - alpha
    ports:
      - 8811:8000
    volumes:
      - dgraph_volume:/dgraph:delegated

volumes:
  dgraph_volume:
