version: "3"
services:
  api:
    build: .
    command: bash -c "go get && go run main.go"
    env_file: ./.env
    ports:
      - "$APP_PORT:$APP_PORT"
    volumes:
      - ./src:/go/src/github.com/doraboateng/api/src
