
type Query {
  alphabets: [Alphabet!]!

  expressions: [Expression!]!

  languages(query: String): [Language!]!
  language(code: String!): Language

  search(query: String!): [SearchResult!]!
}

type SearchResult {
  type: String!
  title: String!
  resourceId: String!
}

# type Mutation {
#   createTodo(input: NewTodo!): Todo!
# }
