
type Query {
  alphabets: [Alphabet!]!

  expressions: [Expression!]!

  languages(query: String): [Language!]!
  language(code: String!): Language
}

# type Mutation {
#   createTodo(input: NewTodo!): Todo!
# }
