name: Build and Publish Docker Image

on:
  push:
    tags:
      - ([0-9]+\.[0-9]+\.[0-9]+)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/build-push-action@v1
      with:
        repository: doraboateng/api
        username: dorabot
        password: ${{ secrets.BOATENG_DOCKER_TOKEN }}
        tag_with_ref: true
        tags: latest
        target: prod
